services:
  api:
    build: .
    container_name: notes_rag_api
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - notes_rag_network

  db:
    image: ankane/pgvector:latest
    container_name: notes_rag_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_rag:/var/lib/postgresql/data
    networks:
      - notes_rag_network

volumes:
  pgdata_rag:

networks:
  notes_rag_network:
    driver: bridge
